name: "Compile to Lua"
on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - run: nix-shell --run "compile"
      - uses: EndBug/add-and-commit@v7
        with:
          add: "lua"
          message: "Update generated lua [skip ci]"
