name: "Compile to Lua"
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "nix/**"
      - "**.nix"
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - run: nix-shell --run "compile"
      - uses: EndBug/add-and-commit@v7
        with:
          add: "lua"
          message: "Update generated lua [skip ci]"
