name: "Niv Update"

on:
  schedule:
    - cron: "5 5 * * 2"

jobs:
  niv-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - run: nix-shell --run "niv update"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: "Update nix deps"
          title: Update nix dependencies with niv
          assignees: jlesquembre
          branch: update-niv
