# on:
#   schedule:
#     - cron: "5 5 * * 5"
on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - run: nix-shell --run "niv update"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@master
        with:
          commit-message: "Update nix deps [skip ci]"
          title: Update nix dependencies with niv
          assignees: jlesquembre
          branch: update-niv
